export const ORDER_ERRORS = {
  EMPTY_CART: 'EMPTY_CART',
  ADDRESS_NOT_FOUND: 'ADDRESS_NOT_FOUND',
  ADDRESS_COORDINATE_REQUIRED: 'ADDRESS_COORDINATE_REQUIRED',
  STORE_NOT_FOUND: 'STORE_NOT_FOUND',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  ORDER_NUMBER_FAILED: 'ORDER_NUMBER_FAILED',
  VOUCHER_NOT_AVAILABLE: 'VOUCHER_NOT_AVAILABLE',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_NOT_CANCELLABLE: 'ORDER_NOT_CANCELLABLE',
  ORDER_NOT_SHIPPABLE: 'ORDER_NOT_SHIPPABLE',
  ORDER_NOT_CONFIRMABLE: 'ORDER_NOT_CONFIRMABLE',
  STOCK_NOT_FOUND: 'STOCK_NOT_FOUND',
  STOCK_MUTATION_NOT_FOUND: 'STOCK_MUTATION_NOT_FOUND',
  STOCK_MUTATION_INVALID_STATUS: 'STOCK_MUTATION_INVALID_STATUS',
  FULFILLMENT_ACCESS_DENIED: 'FULFILLMENT_ACCESS_DENIED',
  INVALID_FULFILLMENT_REQUEST: 'INVALID_FULFILLMENT_REQUEST',
  PAYMENT_PROOF_REQUIRED: 'PAYMENT_PROOF_REQUIRED',
  PAYMENT_PROOF_NOT_ALLOWED: 'PAYMENT_PROOF_NOT_ALLOWED',
  PAYMENT_DEADLINE_EXPIRED: 'PAYMENT_DEADLINE_EXPIRED',
  PAYMENT_GATEWAY_NOT_ALLOWED: 'PAYMENT_GATEWAY_NOT_ALLOWED',
  PAYMENT_GATEWAY_TOKEN_FAILED: 'PAYMENT_GATEWAY_TOKEN_FAILED',
  PAYMENT_GATEWAY_STATUS_SYNC_FAILED: 'PAYMENT_GATEWAY_STATUS_SYNC_FAILED',
  PAYMENT_CONFIRMATION_NOT_ALLOWED: 'PAYMENT_CONFIRMATION_NOT_ALLOWED',
} as const

export type OrderErrorCode = (typeof ORDER_ERRORS)[keyof typeof ORDER_ERRORS]

export class OrderServiceError extends Error {
  code: OrderErrorCode
  statusCode: number
  details?: unknown

  constructor(code: OrderErrorCode, message: string, statusCode = 400, details?: unknown) {
    super(message)
    this.code = code
    this.statusCode = statusCode
    this.details = details
  }
}
